use_frameworks!

target 'CustomPresenter_Example' do
  pod 'CustomPresenter', :path => '../'

  target 'CustomPresenter_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
